### ISSUE TITLE
[BUG] Unintentional(?) modifying of vanilla colors?

### ISSUE THREAD

**Issue by PaperFOlks** [theomenden/TheOmenDen.Vanadium#37]
**Describe the bug**
It seems that Vanadium is messing with the vanilla colors (and more, unable to indentify it as easily) without any particular reason why. I quickly noticed this being the case with biome colors--

Vanilla Plains Color
![Vanilla](https://github.com/theomenden/TheOmenDen.Vanadium/assets/31173350/08c916a7-4b02-4d95-b1e7-f588aeacd2b8)

Vanadium Plains Color
![Vanadium](https://github.com/theomenden/TheOmenDen.Vanadium/assets/31173350/f9c96992-6d7a-47d3-a0f7-90e001bc05a2)

Totally possible I missed something, though unlikely given that I've also isolated it to being a problem with this mod specifically, even with just running it with only the necessary dependencies. 

This was tested on the latest alpha release on Github (0.1.65)

**Comment by AlucardMG36** [comment]
It's semi-intentional as a way to get around sodium's color providers. 
We have to bypass them and provide a sort of recalculation for colors. 

We're working around this problem though, and trying to figure out how to do this without modifying the underlying vanilla behavior. Should hopefully be fixed in 0.1.7

**Comment by PaperFOlks** [comment]
Alright, good to know! Thanks for the info.
